// Code generated by "mockgen"; DO NOT EDIT.
package domain

import "github.com/stretchr/testify/mock"

type AuthServiceMock struct {
	mock.Mock
}

func NewAuthServiceMock() *AuthServiceMock {
	return new(AuthServiceMock)
}

func (_mock *AuthServiceMock) Signup(name string, email string, password string) error {
	_args := _mock.Called(name, email, password)
	_a0 := _args.Error(0)
	return _a0
}
func (_mock *AuthServiceMock) Authenticate(user string, password string) (*Auth, error) {
	_args := _mock.Called(user, password)
	var _a0 *Auth
	if _args.Get(0) != nil {
		if v, ok := _args.Get(0).(*Auth); ok {
			_a0 = v
		}
	}
	_a1 := _args.Error(1)
	return _a0, _a1
}
func (_mock *AuthServiceMock) ParseToken(token string) (*User, error) {
	_args := _mock.Called(token)
	var _a0 *User
	if _args.Get(0) != nil {
		if v, ok := _args.Get(0).(*User); ok {
			_a0 = v
		}
	}
	_a1 := _args.Error(1)
	return _a0, _a1
}

type AuthRepositoryMock struct {
	mock.Mock
}

func NewAuthRepositoryMock() *AuthRepositoryMock {
	return new(AuthRepositoryMock)
}
